name = "progress_indicators"
description = "Ways of displaying progress in command line tools."
version = "0.0.1"
website = "https://github.com/pyjarrett/progress_indicators"
authors = ["Paul Jarrett"]
licenses = "Apache-2.0"

maintainers = ["Paul Jarrett <jarrett.paul.young@gmail.com>"]
maintainers-logins = ["pyjarrett"]
tags = ["command-line", "progress"]

[[depends-on]]  # This line was added by `alr with`
ansiada = "~0.1.0"  # This line was added by `alr with`
